export const requiredFields = [
  "allies",
  "scope",
  "beneficiaries",
  "concepts",
  "description",
  "strategicAxis",
  "endDate",
  "startDate",
  "developmentObjectiveIndicators",
  "generalObjectiveIndicators",
  "justification",
  "implementationPlace",
  "township",
  "preventionLevel",
  "name",
  "developmentObjective",
  "generalObjective",
  "specificObjectives",
  "issueDescription",
  "region",
  "responsible",
  "type"
]

export const fieldsLabels = {
  allies: "Aliados",
  scope: "Ámbitos de intervención",
  beneficiaries: "Beneficiarios",
  concepts: "Conceptos",
  description: "Descripción",
  strategicAxis: "Eje estratégico",
  endDate: "Fecha de conclusión",
  startDate: "Fecha de inicio",
  developmentObjectiveIndicators: "Indicadores de desarrollo",
  generalObjectiveIndicators: "Indicadores generales",
  justification: "Justificación",
  implementationPlace: "Lugar de implementación",
  township: "Municipio",
  preventionLevel: "Nivel de prevención",
  name: "Nombre",
  developmentObjective: "Objetivo de desarrollo",
  generalObjective: "Objetivo general",
  specificObjectives: "Objetivos específicos",
  issueDescription: "Problemática a tratar",
  region: "Región",
  responsible: "Responsable del proyecto",
  type: "Tipo de solicitud"
}
